# Generated by Django 4.2.10 on 2024-03-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Davlat', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='')),
                ('malumot', models.TextField()),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism', models.CharField(max_length=100)),
                ('Familiya', models.CharField(max_length=100)),
                ('Telefon_raqam', models.CharField(max_length=100)),
                ('Sayohat_joyini_tanlang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gallery')),
            ],
        ),
    ]
